### PR TITLE
updated upload and config options to support Pinata uploads

### PR DESCRIPTION
**Pull request by polluterofminds**
This PR adds support for uploading metadata and assets to Pinata. This has been a frequent request of our (Pinata's) customers, and since the Metaplex CLI already supports Infura, it made sense to include Pinata. 

The updates include a config.json file update to include two new properties: 

```
{
...
  "pinataJwt": "API JWT FROM PINATA",
  "pinataGateway": "DEDICATED GATEWAY URL",
...
}
```

The `pinataJwt` property is required, but if the `pinataGateway` property is null, the upload script will point to `https://ipfs.io`.

### CODE REVIEW

**Comment by roederw** [comment]
@polluterofminds can you rebase this? We're going to try and get this merged.

**Comment by polluterofminds** [comment]
> @polluterofminds can you rebase this? We're going to try and get this merged.

Thanks! Fingers crossed, but I think I got this all rebased and ready to go. Let me know if you need any other changes.

**Comment by polluterofminds** [comment]
@austbot whoops! Did that now, thanks!

**Comment by polluterofminds** [comment]
Hey, do you guys need anything else on this PR? @austbot @roederw

**Comment by stegaBOB** [comment]
Looks like some other PRs caused some merge conflicts. Apologies for taking so long to get this in. Would you mind resolving those and I'll merge this in. A lot of the files aren't linted properly, so would you be able to revert that lint for now? Super sorry for the confusion!

**Comment by polluterofminds** [comment]
@stegaBOB @roederw I am closing this PR in favor of a new, cleaned up one that doesn't suffer from all the other PRs that got merged in ahead of this. It should be significantly easier to review. It can be found here: https://github.com/metaplex-foundation/metaplex/pull/1753

**Pull request closed without merging**
