### PR TITLE
[FIX] Remove unexpected extra logical "and" operator

### PR DESCRIPTION
**Pull request by sultanpeyek**
Remove unexpected extra logical `&&` operator that breaking the site.

FYI: @bhgames @bartosz-lipinski this is an urgent fix.
cc: @PigeonSolToken

### CODE REVIEW

**Comment by nathanramli** [comment]
Seems like this happen when @bhgames try to merging the branch.
[https://github.com/metaplex-foundation/metaplex/pull/119/commits/1a087630c4a443b0e29f43acb647e486296be409#diff-939634b09fcebd3d1e942da1a17326485b89bd2d38113776881cd9cf027f2dc7R7-R10](https://github.com/metaplex-foundation/metaplex/pull/119/commits/1a087630c4a443b0e29f43acb647e486296be409#diff-939634b09fcebd3d1e942da1a17326485b89bd2d38113776881cd9cf027f2dc7R7-R10)

**Comment by sultanpeyek** [comment]
Yes you're right @nathanramli 
Removing the extra `&&` solved the problem on my end.

**Comment by bhgames** [comment]
done

**Comment by bhgames** [comment]
yep this one's on me, looks like i can't resolve merge conflicts. Sorry!

**Pull request merged**
