### PR TITLE
fix: yarn build not working

### PR DESCRIPTION
**Pull request by carthanas**
Issue: https://github.com/metaplex-foundation/metaplex/issues/817

Revert unintentional package upgrades from https://github.com/metaplex-foundation/metaplex/commit/492d2df87ddbb6bd84a6c4bd45d20a2d6de90bfa

A lot of packages got upgraded without testing as part of PR https://github.com/metaplex-foundation/metaplex/pull/773
 
This PR reverts the change to yarn.lock while retaining the upgrade of @metaplex/arweave-cost

Testing:
With a broken version of the repo on your machine
```
cd js/
yarn cache clean
lerna clean -y
yarn install
lerna bootstrap

yarn build
```

### CODE REVIEW

**Comment by aheckmann** [comment]
Please rebase

**Comment by bhgames** [comment]
because git was having issues and i couldnt pull this, and it wasnt ready to merge, i just copied the file out. But it did solve our problems. @carthanas today you did the job we should've been doing. You really f-in helped me. Thank you. For this, you get a silver medal. Please give me your wallet to include in the next drop.

**Comment by NFTers** [comment]
Help I tried this 3 times took me about 2 days but still here on this error:
PS C:\Users\Derick\Desktop\metaplex\js> lerna bootstrap
info cli using local version of lerna
lerna notice cli v3.22.1
lerna info versioning independent
lerna info bootstrap root only
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 9.47s.
PS C:\Users\Derick\Desktop\metaplex\js> yarn build
yarn run v1.22.17
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 4 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@oyster/common' in 133.9s:
$ run-s build-ts build-css
$ tsc
$ less-watch-compiler src/ dist/lib/ --run-once
Running less-watch-compiler once.
lerna info run Ran npm script 'build' in '@metaplex/cli' in 173.1s:
$ tsc -p ./src
lerna ERR! yarn run build exited 1 in 'web'
lerna ERR! yarn run build stdout:
$ next build
info  - Loaded env from C:\Users\Derick\Desktop\metaplex\js\packages\web\.env.production   
info  - Loaded env from C:\Users\Derick\Desktop\metaplex\js\packages\web\.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.       

lerna ERR! yarn run build stderr:
Failed to compile.

./src/views/analytics/index.tsx:253:34
Type error: Type '{ scales: { yAxes: { ticks: { beginAtZero: boolean; }; }[]; }; }' is not 
assignable to type '_DeepPartialObject<CoreChartOptions<"bar"> & ElementChartOptions<"bar"> & PluginChartOptions<"bar"> & DatasetChartOptions<"bar"> & ScaleChartOptions<...> & BarControllerChartOptions>'.
  Types of property 'scales' are incompatible.
    Type '{ yAxes: { ticks: { beginAtZero: boolean; }; }[]; }' is not assignable to type '_DeepPartialObject<{ [key: string]: ScaleOptionsByType<keyof CartesianScaleTypeRegistry>; }>'.
      Property 'yAxes' is incompatible with index signature.
        Type '{ ticks: { beginAtZero: boolean; }; }[]' is not assignable to type '_DeepPartialObject<{ type: "time"; } & CartesianScaleOptions & { bounds: "data" | "ticks"; adapters: { date: unknown; }; time: { parser: string | ((v: unknown) => number); round: false | TimeUnit; ... 5 more ...; minUnit: TimeUnit; }; ticks: { ...; }; }> | ... 4 more ... | undefined'.
          Type '{ ticks: { beginAtZero: boolean; }; }[]' is not assignable to type '_DeepPartialObject<{ type: "timeseries"; } & CartesianScaleOptions & { bounds: "data" | "ticks"; adapters: { date: unknown; }; time: { parser: string | ((v: unknown) => number); round: false | TimeUnit; ... 5 more ...; minUnit: TimeUnit; }; ticks: { ...; }; }>'.
            Types of property 'reverse' are incompatible.
              Type '() => { ticks: { beginAtZero: boolean; }; }[]' is not assignable to type 'boolean | undefined'.
                Type '() => { ticks: { beginAtZero: boolean; }; }[]' is not assignable to type 'true'.

  251 |     };
  252 | 
> 253 |     return <Bar data={histoData} options={histoOptions} />;
      |                                  ^
  254 |   },
  255 | );
  256 | 
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'web'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.       
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by carthanas** [comment]
@bhgames Wow, thanks man thats very kind of you!

I'm happy to help, let me know if theres anything else I can do.


Sol Address: `8zdipZL4jusUa7y56UsbGvLHXeNhqLHDWzzg9wJnEuT6`

**Pull request closed without merging**
