### PR TITLE
Chore: fix dependency issues, cleanup, pin yarn version

### PR DESCRIPTION
**Pull request by 21e8**
I could not sleep after the last PR cause I had a hunch at how much stuff might be out of order here.
The gumdrop dependencies are a wild mess. 

- enforce same yarn version (prevents errors a la `expected workspace package to exist for`)
- upgrade some dependencies 
  - migrated jazzicon@1.5 to @metamask/jazzicon@2 because of deprecation
  - migrated bundlr imports
- remove some unused dependencies
- move test and @types libs to devDependencies

### CODE REVIEW

**Comment by 21e8** [comment]
Why am I doing this? Cause this way it is a tiny bit more feasible to run the packages individually instead of running `lerna` across everything which nowadays can take quite a while

**Comment by stegaBOB** [comment]
@21e8 Thank you again for doing this. I'll try to take a look at this tomorrow. As for gumdrop, it has a ton of issues right now and is being revamped with #1794. Just waiting on some follow up on docs stuff.

**Comment by 21e8** [comment]
@stegaBOB no problem, take your rest. I needed some distraction. I checked the result by removing all node_modules and lockfiles and then rerun `yarn bootstrap && yarn run build` and that checked out.

happy to go over the deps from time to time and check if still needed and mebbe reduce security risk and install times a bit.

**Comment by stegaBOB** [comment]
Just ran some tests! Gumdrop is still broken like usual, but that PR I linked earlier should fix it. Thanks again for these improvements. Merging in now!

**Review by stegaBOB — APPROVED** [review]

**Comment by 21e8** [comment]
ty ser

**Comment by stegaBOB** [comment]
Hey @21e8 just looking at this again now. Missed it when it was merged in a bit ago somehow, but is there a reason you removed those lockfiles? Unless I'm missing something those should have been kept right?

**Comment by 21e8** [comment]
@stegaBOB 
I was under the impression that the `lerna bootstrap` would create a collective yarn.lock but I might be wrong here.
tbh one of the main reasons for this PR is my frustration of not being able to install anything when trying to pull one of the packages out of the nonorepo due to it being a complete mess all over the place.

**Comment by 21e8** [comment]
I am really hoping that you guys break up this repo and make `@oyster/common` an actual package, no single person can longer oversee what is happening in this huge monorepe.

I am seeing that token-entangler and candy-machine-ui are excluded from lerna builds. Why?

**Comment by stegaBOB** [comment]
Not sure why token entangler was excluded tbh. The ui was excluded because lerna was causing some issues and was causing it to break. As for splitting up the repo, soonTM

**Comment by stegaBOB** [comment]
I'll open a PR to add those lockfiles back in

**Comment by stegaBOB** [comment]
actually @21e8 would you mind adding those back in in your latest deps PR so I can merge that in together? The package.json files didn't change so the lockfiles should be identical

**Comment by stegaBOB** [comment]
Actually nevermind I'll add those in with a related PR

**Pull request merged**
