### PR TITLE
allow candy machine price update

### PR DESCRIPTION
**Pull request by BertrandBev**

### CODE REVIEW

**Comment by mihaiserban** [comment]
Is this feature working?
Can’t test minting in this fork, getting has_one contraint violated error

**Comment by mihaiserban** [comment]
Managed to update price, took the latest master, and created a new program in cli.tsx following your PR. 👌🏻

**Comment by bhgames** [comment]
Please submit follow up PR updating readme. @levicook please update article. Please also send me your wallet for medal.

**Comment by BertrandBev** [comment]
Sure! https://github.com/metaplex-foundation/metaplex/pull/410

**Comment by bhgames** [comment]
Sent!

**Pull request merged**
