### PR TITLE
update README

### PR DESCRIPTION
**Pull request by BertrandBev**
Update README following [#347](https://github.com/metaplex-foundation/metaplex/pull/347)

### CODE REVIEW

**Comment by bhgames** [comment]
Send me your wallet again bud

**Comment by BertrandBev** [comment]
> Send me your wallet again bud

Sure thing! 5QLZnmMpT4hZW5hJ5pvHBStdGdgCvGjXidxhAMPQe15m

**Comment by bhgames** [comment]
@BertrandBev which one do you already have?

**Comment by BertrandBev** [comment]
> @BertrandBev which one do you already have?

I got a beautiful HoMR: AGx1 2nd Place :)

**Comment by bhgames** [comment]
delivered

**Pull request merged**
