### PR TITLE
bump bundlr package to v0.5.8

### LINKED ISSUE #1643: Fix for 429 Too many requests using arweave-sol HERE!
So,
arweave-sol uses bundlr to upload the images.
The bundlr node module has the default solana mainnet RPC hardcoded during uploads. That is why you get limited even with a custom RPC.

To fix this error, open:
`metaplex\js\packages\cli\node_modules\@bundlr-network\client\build\src\currencies\solana.js` and change line 14 to:
`return new web3.Connection("YOUR RPC URL", "confirmed");`

Unfortunately it seems like bundlr doesn't support a custom RPC so you will have to do this everytime you update your packages or try to use arweave-sol. At least for now...

### PR DESCRIPTION
**Pull request by samuelvanderwaal**
Fixes #1643 and numerous community issues in Discord.

### CODE REVIEW

**Comment by aheckmann** [comment]
All checks pass. How was this tested and what does it fix? An issue links?

**Comment by aheckmann** [comment]
NVM, CI covers candy machine. Nice

**Review by aheckmann — APPROVED** [review]

**Comment by samuelvanderwaal** [comment]
> All checks pass. How was this tested and what does it fix? Any issue links? Change LGTM

This bumps the Bundlr version to fix a problem with RPC timeouts. It was tested by running multiple candy machines with the `arweave-sol` storage method using our candy machine test script.

**Comment by samuelvanderwaal** [comment]
> NVM, CI covers candy machine. Nice

CI only covers the candy-machine-ui deploy. We have a test script in `js/packages/cli/test` that we use to manually create candy machines to test CLI changes.

**Pull request merged**
