### PR TITLE
Revert "upgrade @metaplex/arweave-cost module"

### PR DESCRIPTION
**Pull request by bhgames**
This reverts commit 492d2df87ddbb6bd84a6c4bd45d20a2d6de90bfa.

@aheckmann had to revert this commit, as it breaks fair launch. Not sure why, but it does. For now, since it's an outage, going to revert it.

### CODE REVIEW

**Comment by aheckmann** [comment]
Any version of arweave-cost < 1.0.4 will break web. It's probably something else in yarn lock. arweave-cost is part of the pricing fix so needs to remain. Spent a long time yesterday looking into why`yarn build` isn't working too but haven't gotten to the bottom of it yet.

**Comment by aheckmann** [comment]
Are there any documented or automated tests for FLP? Having this will help us avoid future breakages. Need to get CI working for every feature

**Comment by bhgames** [comment]
You don't need automated tests to run yarn start

**Comment by bhgames** [comment]
This commit does break web, so I'm back to square one. Closing this. Have to fix it on master.

**Comment by aheckmann** [comment]
> You don't need automated tests to run yarn start

yarn start worked. No tests means thing break. CI has been broken on this project for weeks. Everyone is guessing.

**Pull request closed without merging**
