### PR TITLE
Allow override of sol wallet address

### PR DESCRIPTION
**Pull request by richard-fisher**
Add optional param to set a different SOL wallet address to receive mint funds

### CODE REVIEW

**Comment by bhgames** [comment]
Love it. @ me in a comment withy our wallet address.

**Comment by richard-fisher** [comment]
Thanks @bhgames 2eBBNzw7DeWuYfWhPVGanm7VyYogiWKjSRcAHhcDFSMd

**Comment by bhgames** [comment]
sent

**Comment by grimAgent** [comment]
Hey @richard-fisher is the `--sol-treasury-account` working as expected? When I try to use it, I run into this error: https://github.com/metaplex-foundation/metaplex/issues/535

But if I remove that option, everything works just fine (but funds go to minting authority of course) 

Did you get to try this out @bhgames ?

**Comment by richard-fisher** [comment]
Commented on the issue

**Pull request merged**
