### PR TITLE
Align lifetime of process_instruction with solana

### LINKED ISSUE #446: Cannot use `spl_token_metadata` with `solana_program_test`
Hello,
I am trying to combine a basic example of `solana_program_test` utility with the `spl_token_metadata` program, like so:

```rust
use solana_program_test::{tokio, processor, ProgramTest},

#[tokio::test]
async fn my_test() {
    // ...
    let mut program = ProgramTest::default();
    program.add_program(
        "spl_token_metadata",
        spl_token_metadata::ID,
        processor!(spl_token_metadata::processor::process_instruction),
    );
    // ...
}
```

But because of constraints enforced on lifetimes by the metadata entry point ([see here](https://github.com/metaplex-foundation/metaplex/blob/master/rust/token-metadata/program/src/processor.rs#L40)), I get the following error:

```
error[E0308]: mismatched types
   --> tests/my_test.rs:269:20
    |
269 |         processor!(spl_token_metadata::processor::process_instruction),
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
    |
    = note: expected fn pointer `for<'r, 's, 't0, 't1> fn(&'r Pubkey, &'s [AccountInfo<'t0>], &'t1 [u8]) -> Result<_, _>`
               found fn pointer `for<'a, 'r> fn(&'a Pubkey, &'a [AccountInfo<'a>], &'r [u8]) -> Result<_, _>`
```

I tried many things such as wrapping the entrypoint or expanding the `processor!` macro but could not change the core error. :/
Anybody is using `solana_program_test`? How do you do it?

### PR DESCRIPTION
**Pull request by Gerhut**
Fixes #446
Ref: <https://docs.rs/solana-program/1.8.1/solana_program/entrypoint/type.ProcessInstruction.html>

### CODE REVIEW

**Comment by theonekeyg** [comment]
@austbox @bhgames Could you please review this PR? This is a very easy fix for a really annoying issue.

**Comment by theonekeyg** [comment]
@austbox @bhgames Could you please review this PR? This is a very easy fix for a really annoying issue.

**Comment by thlorenz** [comment]
Nice, I actually tried to do this myself at some point in order to easier test the processor however the lifetimes go all the way down and aren't easily removed.

I checked out your changes and am running into the following issues, in both cases compiler complaining about lifetimes not matching:

### Building Metaplex

```sh
cd rust/metaplex/program/
cargo build
```

```
error[E0623]: lifetime mismatch
  --> token-metadata/program/src/processor.rs:51:17
   |
42 |     accounts: &[AccountInfo],
   |               -------------- these two types are declared with different lifetimes...
...
51 |                 accounts,
   |                 ^^^^^^^^ ...but data from `accounts` flows into `accounts` here

error[E0623]: lifetime mismatch
  --> token-metadata/program/src/processor.rs:74:29
   |
42 |     accounts: &[AccountInfo],
   |               -------------- these two types are declared with different lifetimes...
...
74 |                 program_id, accounts,
   |                             ^^^^^^^^ ...but data from `accounts` flows into `accounts` here

error[E0623]: lifetime mismatch
   --> token-metadata/program/src/processor.rs:116:17
    |
42  |     accounts: &[AccountInfo],
    |               -------------- these two types are declared with different lifetimes...
...
116 |                 accounts,
    |                 ^^^^^^^^ ...but data from `accounts` flows into `accounts` here

error[E0623]: lifetime mismatch
   --> token-metadata/program/src/processor.rs:129:17
    |
42  |     accounts: &[AccountInfo],
    |               -------------- these two types are declared with different lifetimes...
...
129 |                 accounts,
    |                 ^^^^^^^^ ...but data from `accounts` flows into `accounts` here

For more information about this error, try `rustc --explain E0623`.
error: could not compile `metaplex-token-metadata` due to 4 previous errors
```

<details>
### Building Token Metadata

```sh
cd rust/token-metadata/program
cargo build
```

<summary> Compiler errors:
<details>
```
error[E0623]: lifetime mismatch
  --> token-metadata/program/src/processor.rs:51:17
   |
42 |     accounts: &[AccountInfo],
   |               -------------- these two types are declared with different lifetimes...
...
51 |                 accounts,
   |                 ^^^^^^^^ ...but data from `accounts` flows into `accounts` here

error[E0623]: lifetime mismatch
  --> token-metadata/program/src/processor.rs:74:29
   |
42 |     accounts: &[AccountInfo],
   |               -------------- these two types are declared with different lifetimes...
...
74 |                 program_id, accounts,
   |                             ^^^^^^^^ ...but data from `accounts` flows into `accounts` here

error[E0623]: lifetime mismatch
   --> token-metadata/program/src/processor.rs:116:17
    |
42  |     accounts: &[AccountInfo],
    |               -------------- these two types are declared with different lifetimes...
...
116 |                 accounts,
    |                 ^^^^^^^^ ...but data from `accounts` flows into `accounts` here

error[E0623]: lifetime mismatch
   --> token-metadata/program/src/processor.rs:129:17
    |
42  |     accounts: &[AccountInfo],
    |               -------------- these two types are declared with different lifetimes...
...
129 |                 accounts,
    |                 ^^^^^^^^ ...but data from `accounts` flows into `accounts` here

For more information about this error, try `rustc --explain E0623`.
error: could not compile `metaplex-token-metadata` due to 4 previous errors
```
</details>
</summary>

**Comment by thlorenz** [comment]
Closing for now as it doesn't compile. Please feel free to submit a version that compiles. Thanks!

**Pull request closed without merging**
