### PR TITLE
graphQL api server

### PR DESCRIPTION
**Pull request by exromany**
creates package for GraphQL server - node.js app that will cache meta-data and return it in convinient way
This PR does not change client's work. Client will be changed in a separate PR (#236) after graphql server is deployed.

- [x] prepare codebase to use on server
  - move `models/metaplex` to common pkg
  - move `contexts/meta` to common pkg
  - split `contexts/accounts` into separated files
  - wrap using of localStorage into ssr-ready hook
  - meta keeps all creators (if `all` flag specified)
- [x] setup GraphQL server with Apollo-Server & Nexus
- [x] works with different endpoints (mainnet-beta, testnet, devnet)
- [x] get artworks by store, owner, creator
- [x] loading user tokens during request serving
- [x] get auctions by store Id & filters
- [x] added Dockerfile for api 
 

🤖  plans to realize after this PR
- updates with Subscription
- rework storing data object (MetaState) (after #236)

🦶  steps:

- https://github.com/metaplex-foundation/metaplex/pull/312
- https://github.com/metaplex-foundation/metaplex/pull/313
- https://github.com/metaplex-foundation/metaplex/pull/314
- https://github.com/metaplex-foundation/metaplex/pull/315
- https://github.com/metaplex-foundation/metaplex/pull/316
- https://github.com/metaplex-foundation/metaplex/pull/317
- https://github.com/metaplex-foundation/metaplex/pull/319
- https://github.com/metaplex-foundation/metaplex/pull/339

### Updates
- Fix bug with very big request https://github.com/solana-labs/solana/pull/19821

### CODE REVIEW

**Comment by kespinola** [comment]
A lot of cool stuff happening in this PR. Seeing SDK shaping up and friendly domain objects work with for client applications.

Do you mind adding some goals and requirements in the description? Love to follow along.

**Comment by exromany** [comment]
@bartosz-lipinski it can be merged

**Comment by exromany** [comment]
@bhgames can you look at this?

**Comment by whiteyhat** [comment]
@exromany what is the status of this?

**Comment by bhgames** [comment]
I think it is pretty much done he is just waiting on us to have time to review it - it is truly massive change.

**Comment by whiteyhat** [comment]
@bhgames thanks for the reply 👍

**Comment by bhgames** [comment]
@exromany There is so much here and in the other PRs, I am leaning towards just deploy it somewhere and run the cryptokickers store using the graphql. If it is all working, I am inclined to just merge it all. It's too big to properly review well given our time constraints, and honestly you are one of the devs I trust the most. So let's just battlefield test it using one of our largest stores.

**Comment by exromany** [comment]
@bhgames great idea

**Comment by exromany** [comment]
preparing to deploy some stage graphql server

**Pull request closed without merging**
