### PR TITLE
another overhaul

### PR DESCRIPTION
**Pull request by WrRaThY**
- added backend signing for a single metadata id
- some small refactoring
- extracted upload from the CLI (maybe will do the same with other methods)
- automatic re-uploading on failures

### CODE REVIEW

**Comment by bhgames** [comment]
@WrRaThY I will blind merge this if you give me a video using it to do a full candy machine creation-through-drop using mint token till it runs out of units with a 5-drop via screen share. Dont have time to review right now.

**Comment by WrRaThY** [comment]
@bhgames there it goes ;) 
https://youtu.be/zlj8tNyP3V0

I think that actually reading the code would've been faster for the both of us, but there it is - a video PR walk-through ;)

**Comment by bhgames** [comment]
You did forget to verify that verify worked though. If you can verify with a gh comment that verify still works (that you tested it on your honor) then I will give this a merge :) And you'll need to let me know which of the medals you already have so I can give you one of the other ones. ;)

**Comment by WrRaThY** [comment]
@bhgames 
image

I have only one :P  
image

**Comment by bhgames** [comment]
Coolio - what's your wallet? will send you another :)

**Comment by WrRaThY** [comment]
I believe we had a chat on telegram lately with bartosz.
anyway, it's `85frGYyMRhzKEgWWNeZuEyg4LkWWkofBFAQhyo88iUSj`
cheers :)

**Comment by bhgames** [comment]
Alright, confirm receipt :) @WrRaThY

**Comment by WrRaThY** [comment]
Got it, thanks!

**Comment by AnalyticsNinja** [comment]
It's not working , please revert or you will have a lot of complains.
Tested on Linux and MacOs, creates a bug on upload.
You get this from candy machine program : 
`'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 24251 out of range for slice of length 255', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'`

When I test the previous cli from a couple of days ago. It works, so it's not coming from the onchain candy machine program

**Comment by bhgames** [comment]
Well how about you submit a pull request @AnalyticsNinja

**Comment by AnalyticsNinja** [comment]
> Well how about you submit a pull request @AnalyticsNinja

I'm a noob, i just know it's not working anymore. And commented here.

**Comment by WrRaThY** [comment]
I tested this a number of times. You can even see a verification video up there. 
Please be more specific about the problem so I can fix it

**Comment by AnalyticsNinja** [comment]
This is what I get when I put upload.
If I do the same command on the previous metaplex, it works, so it isn't from the json file.
I do modify one element from "upload.ts", and it's just for bypassing arweave, and using s3 instead. But same modification works on previous version.

`$ metaplex upload ./assets --env devnet --keypair ~/.config/solana/devnet1.json
started at: 1631566607736
wallet public key: 5TbEUCRwXE1DydSERh81ZWSFZDnZWHhSmZKApe1tCx6p
program id from anchor cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ
Processing file: 0
initializing config
initialized config for a candy machine with publickey: 2sJGhVXY3ZZhpQCVh4NLxu6VXLDXUzws3wQ4ELDxyroC
Writing indices 0-3
Transaction simulation failed: Error processing Instruction 0: Program failed to complete 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: libstd rust_begin_panic
    Program log: panicked at 'range end index 1211 out of range for slice of length 255', nft-candy-machine/src/lib.rs:318:18
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as addConfigLines] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 1211 out of range for slice of length 255', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}
saving config line 0-3 failed SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as addConfigLines] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 1211 out of range for slice of length 255', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}
Done. Successful = false.
upload was not successful, rerunning
`

**Comment by AnalyticsNinja** [comment]
I rchanged "upload.ts" to original and removed my s3 modification. And still the same problem

**Comment by AnalyticsNinja** [comment]
Sorry to spam but the problem is there is a new arg, so if you don't put  -n x on upload command, you have the error I showed before.
Since the tutorial doesn't add this arg, I think a lot of people will have the same issue.

So this crashes : metaplex upload ./assets --env devnet --keypair ~/.config/solana/devnet1.json

But this works : metaplex upload ./assets --env devnet --keypair ~/.config/solana/devnet1.json -n 4

**Comment by WrRaThY** [comment]
cool, I'll fix that quickly.
some feedback for you: you may want to paste a `formatted `output log, otherwise it's unreadable

**Comment by WrRaThY** [comment]
@bhgames @AnalyticsNinja @milezzz 
https://github.com/metaplex-foundation/metaplex/pull/389

**Pull request merged**
