### PR TITLE
Fixed displaying winning bid

### PR DESCRIPTION
**Pull request by ikadushkina**
Task: https://github.com/metaplex-foundation/metaplex/issues/783
+ Removed end time for instant sale (https://app.asana.com/0/1201289799176936/1201475155738502)
Result:
Снимок экрана 2021-12-27 в 16 49 25

Снимок экрана 2021-12-27 в 16 53 10

### CODE REVIEW

**Review by zaxozhu — APPROVED** [review]

**Comment by roederw** [comment]
Do we still need this?

**Comment by stegaBOB** [comment]
I think this is a good to have fix. Not sure why it hasn't been merged in yet. @ikadushkina @zaxozhu should we merge this in?

**Comment by zaxozhu** [comment]
It works but does impact the loading speed of the home page.

**Comment by stegaBOB** [comment]
How much of an impact? We are bottlenecked by the rpc requests right now right? In your opinion is it worth merging in @zaxozhu?

**Comment by yamijuan** [comment]
This PR is super useful if it does not slow down too much the loading time, we are testing it in one of the partner's repos. @stegaBOB

**Comment by zaxozhu** [comment]
@yamijuan Thanks for the response, please check. 
Sorry guys didn't get a notification.

**Comment by stegaBOB** [comment]
I was getting some type issues when trying to test it on a local storefront
yesterday. I'll retry today and see if anything is different.

**Comment by stegaBOB** [comment]
@austbot last I checked it was broken. I'll test it again though

**Comment by stegaBOB** [comment]
Tested it again and it appears to be working well! Merging this in.

**Pull request merged**
