### PR TITLE
Add symbol validation to createCandyMachineV2

### PR DESCRIPTION
**Pull request by saito-kosuke**
fix: #1616

### CODE REVIEW

**Review by stegaBOB — APPROVED** [review]
Looks good! Thanks

**Comment by RidhwanDev** [comment]
I have symbol, this still fails.

**Comment by saito-kosuke** [comment]
Could you share your config file?

**Comment by RidhwanDev** [comment]
```{
    "name": "Number #0001",
    "symbol": "NB",
    "description": "Collection of 10 numbers on the blockchain. This is the number 1/10.",
    "seller_fee_basis_points": 500,
    "image": "0.png",
    "attributes": [
        {"trait_type": "Layer-1", "value": "0"},
        {"trait_type": "Layer-2", "value": "0"}, 
        {"trait_type": "Layer-3", "value": "0"},
        {"trait_type": "Layer-4", "value": "1"}
    ],
    "properties": {
        "creators": [{"address": "MY-ADDRESS", "share": 100}],
        "files": [{"uri": "0.png", "type": "image/png"}]
    },
    "collection": {"name": "numbers", "family": "numbers"}
}```

**Comment by saito-kosuke** [comment]
@RidhwanDev looks good.
Could you check your assets via [this tool](https://support.coinfra.io/tutorials/step2-option-how-to-check-assets-of-metaplex-candy-machine) for free?

**Comment by RidhwanDev** [comment]
@saito-kosuke I checked it on your tool, looks fine uploaded fine. Nice tool btw! I'm also trying to make candy-machine-v2 work from a react app. Can't get past this issue.

**Comment by oboxodo** [comment]
@stegaBOB I think this commit should be reverted because it fails uploads when metadata has `symbol: ""` (empty string) but that value is actually valid. I could be wrong but there's nothing in the standard indicating a non-empty value MUST be used, and there's plenty valid NFTs in the wild with empty string symbols.

**Comment by oboxodo** [comment]
@stegaBOB that shouldn't be necessary because Typescript already checks for a `string`.

**Comment by stegaBOB** [comment]
Ah I think I misunderstood the issue then. It looks like we should probably change that type to be `string | undefined` and then convert that to `""` if undefined to satisfy the types needed for the candy machine on chain data.

**Comment by oboxodo** [comment]
That works for me as long as I'm able to either avoid having a `symbol` at all or set it as a blank string :man_shrugging: :sweat_smile:. This merged commit broke that so I'm having to comment these lines locally to upload stuff.

**Comment by VeryCrazyDog** [comment]
> @stegaBOB that shouldn't be necessary because Typescript already checks for a `string` in `CandyMachineData` [here](https://github.com/saito-kosuke/metaplex/blob/2a03bb668dd834b34f815cc3858b5d462094aa90/js/packages/cli/src/helpers/accounts.ts#L85).

@oboxodo Not quite, TypeScript won't magically perform string check. As you can see [here](https://github.com/metaplex-foundation/metaplex/blob/631983372cfbdfa99a45c26141f8756cd77efc99/js/packages/cli/src/commands/upload.ts#L487), `symbol` is casted as string without being checked.

@stegaBOB I have created PR #2105 to resolve the issue.

**Comment by stegaBOB** [comment]
If symbol isn't in the manifest it should set the symbol to "" fyi. Other than that looks good to me I think. I'll comment this there too

**Comment by VeryCrazyDog** [comment]
Personally I prefer throwing error when symbol is not defined, so that user will notice they still have `symbol` need to set.

Having a default empty string value will just silent the error.

I can update the PR if default empty string value is the final decision.

**Comment by VeryCrazyDog** [comment]
I just updated the PR to throw `TypeError` instead of `Error`, which I think is more appropriate.

**Pull request merged**
