### PR TITLE
Re-add testing tools to the build path

### LINKED ISSUE #54: Re-add the testing tools to the build path
All 4 programs (metaplex, auction, token-vault, token-metadata) also include a test CLI tool, but these have been removed from the build path due to some version mismatches with spl-token. These aren't an issue anymore so they can be re-added to the build path and used as a different way of learning how the contracts work.

### PR DESCRIPTION
**Pull request by praskoson**
Added the testing tools back to the build path. 
Also corrected the default RPC URLs, as the outdated ones were being used.

Fix #54

### CODE REVIEW

**Comment by bhgames** [comment]
We recently moved Vault to using a Key enum...the scripts haven't been updated to do that so this won't build. Can you make that update here?

**Review by bhgames — CHANGES_REQUESTED** [review]
Needs fixes to scripts to have latest Key enum changes for Vault contract

**Comment by praskoson** [comment]
I updated it, mind taking a look @bhgames?

**Comment by bhgames** [comment]
This is gonna sound stupid, but I swear you're almost there :)

image

Just re-arrange the imports to get rustfmt to pass. We already aren't passing clippy, for which I feel guilty, but at least our vscode editors are keeping rustfmt auto-passing. Let's not fail that one too :D

**Comment by praskoson** [comment]
I have to admit I didn't even know of rustfmt until now x)
Anyways, added those changes in the last commit.

**Review by bhgames — APPROVED** [review]

**Pull request merged**
