### PR TITLE
Instant sale

### PR DESCRIPTION
**Pull request by bhgames**

### CODE REVIEW

**Comment by luke-devel** [comment]
Any ETA on this PR to main branch?

**Comment by whiteyhat** [comment]
This looks great. Any ETA for this?

**Comment by adamjeffries** [comment]
> This looks great. Any ETA for this?

PR is ready - just being reviewed

**Comment by bperin** [comment]
This seems run locally but not when I do yarn build
```
./src/components/AuctionCard/index.tsx:545:23
Type error: Argument of type 'BN | null | undefined' is not assignable to parameter of type 'number | BN'.
  Type 'undefined' is not assignable to type 'number | BN'.

  543 |                       auctionView,
  544 |                       accountByMint,
> 545 |                       auctionView.auctionDataExtended?.info.instantSalePrice,
      |                       ^
  546 |                     );
  547 |                     setLastBid(bid);
  548 |                   } catch (e) {
error Command failed with exit code 1.
```

**Pull request merged**
