### PR TITLE
enhancement: Fetch prices in parallel

### PR DESCRIPTION
**Pull request by steveluscher**
Right now, we fetch prices in a loop on startup. Because we `await` the price on every iteration of the loop, we have to wait for the current price fetch to return before we can start the next one.

In this PR, we collect _promises_ for the price data in a loop, let them all start in parallel, then `await` the results afterward.

Before, we would make all of the network requests in serial.

bad

After, every price request gets fired at the same time, reducing the total end-to-end time.

good

### CODE REVIEW

**Comment by steveluscher** [comment]
Hey, @austbot! Jordan said you might be a good person to tag to find reviewers for #1075, #1077, #1086, and #1087.

**Comment by steveluscher** [comment]
That sounds good! I can’t bang that out today, but possibly in the next few days. Certainly after Jan 10.

**Comment by steveluscher** [comment]
When do you expect 1.1.0 to go to `master`?

**Comment by steveluscher** [comment]
> can you target these fixes to that branch ?

I rebased #1087, #1086, #1077, and #1075 atop release/v1.1.0 just now, if that's helpful @austbot.

**Comment by roederw** [comment]
@steveluscher can you re-target all your PRs to `master`?

**Comment by steveluscher** [comment]
test

**Comment by steveluscher** [comment]
Retargeted to `master`.

**Comment by stegaBOB** [comment]
Going to review this PR tomorrow. Thanks!

**Review by stegaBOB — APPROVED** [review]
Another easy improvement to review! Thanks again!

**Pull request merged**
